version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-translate
    ports:
      - "2342:11434"
    volumes:
      - ./models:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu] 